services:
  app:
    image: golang:1.24-alpine
    container_name: golang_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: ['go', 'run', 'main.go']

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crud_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
