services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:pass@db:5432/postgres?sslmode=disable # строка подключения
      HTTP_SERVER_PORT: 3000
