services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      PGDATA: /usr/local/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default-dev-network
    volumes:
      - $PWD/db_data:/usr/local/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      DB_URL: postgres://postgres:pass@db:5432/postgres?sslmode=disable
      HTTP_SERVER_PORT: 3000
    networks:
      - default-dev-network

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    networks:
      - default-dev-network

networks:
  default-dev-network:
    external: true
